### ISSUE TITLE
Spatially Distributed Heat Transfer

### ISSUE THREAD

**Issue by quorx** [mtiller/ModelicaBook#402] opened 2018-01-05 21:56 UTC
http://book.xogeny.com/components/subsystems/heat_transfer/
`model Rod "Modeling discretized rod"`...

line
`HTC.ThermalConductor rod_conduction[n-1](each final G=G_rod)`
should be:
`HTC.ThermalConductor rod_conduction[n-1](each final G=G_rod*(n-1))`

Great book! Thanks,

**Comment by tbeu** [comment] 2019-09-14 18:50
Duplicate of #311 and addressed by 318206d6302a225c822a476d9faa3348885352a1.

**Closed** 2019-09-15 21:54 UTC
